- name: cloudtack-setup-databases
  shell: cloudstack-setup-databases cloud:cloud123@localhost --deploy-as=root && touch /etc/ansible_state/cloudstack_setup_databases_ready
  args:
    creates:
      /etc/ansible_state/cloudstack_setup_databases_ready

- name: cloudstack-setup-management
  shell: cloudstack-setup-management && touch /etc/ansible_state/cloudstack_setup_management_ready
  args:
    creates:
      /etc/ansible_state/cloudstack_setup_management_ready

- name: cloudtack-setup-templates
  shell: /usr/share/cloudstack-common/scripts/storage/secondary/cloud-install-sys-tmplt -m /export/secondary -u http://download.cloudstack.org/systemvm/4.14/systemvmtemplate-4.14.0-kvm.qcow2.bz2 -h kvm -F && touch /etc/ansible_state/cloudstack_setup_templates_ready
  args:
    creates:
      /etc/ansible_state/cloudstack_setup_templates_ready

- name: Start CloudStack Management Service
  service:
    name: "{{ role_app_acs_mgmt_service }}"
    state: started

- name: Enable CloudStack Management Service.
  service:
    name: "{{ role_app_acs_mgmt_service }}"
    enabled: yes
