- name: Assure Ansible locks directory exists
  file:
    name: /etc/ansible_locks
    state: directory

- name: cloudtack-setup-databases
  shell: cloudstack-setup-databases cloud:{{ role_app_acs_mgmt_cloudpassword }}@localhost --deploy-as=root:{{ role_app_acs_mgmt_databasepassword }} && touch /etc/ansible_locks/databases_ready
  args:
    creates:
      /etc/ansible_locks/databases_ready

- name: cloudstack-setup-management
  shell: cloudstack-setup-management && touch /etc/ansible_locks/management_ready
  args:
    creates:
      /etc/ansible_locks/management_ready
