- name: Assure Ansible locks directory exists
  file:
    name: /etc/cloudstack_ansible_locks
    state: directory

- name: cloudtack-setup-templates
  shell: >-
    /usr/share/cloudstack-common/scripts/storage/secondary/cloud-install-sys-tmplt
    -m /export/secondary -u http://download.cloudstack.org/systemvm/4.14/systemvmtemplate-4.14.0-kvm.qcow2.bz2 -h kvm -F
    && touch /etc/cloudstack_ansible_locks/templates_ready
  args:
    creates:
      /etc/cloudstack_ansible_locks/templates_ready
