- name: Create Repositories
  import_role:
    name: role_mod_repositories
  vars:
    - role_mod_repositories_yum_repos:
        - name: CloudStack-ShapeBlue
          description: "ShapeBlue CloudStack Repository."
          file: "CloudStack-ShapeBlue"
          baseurl: "http://packages.shapeblue.com/cloudstack/upstream/centos7/4.14"
          gpgcheck: "yes"
          gpgkey: "http://packages.shapeblue.com/release.asc"
          enabled: "yes"

